---
- name: Show facts (testing)
  hosts:
    - observium_server
    - zabbix_agent
    - zabbix_server
    - zabbix_db
  tasks:
    - name: Show ansible_facts
      ansible.builtin.debug:
        var: ansible_facts
