---
- name: Show facts for Zabbix servers and support hosts
  hosts:
    - zabbix_server
    - zabbix_db
  tasks:
    - name: Show ansible_facts
      ansible.builtin.debug:
        var: ansible_facts
