---
- name: Install prerequisite packages
  apt:
    name:
      - gpg
      - ntp
    state: latest
    update_cache: yes
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: Restart NTP services
  ansible.builtin.systemd:
    state: started
    daemon_reload: yes
    enabled: yes
    masked: no
    name: ntp
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: Check ca-certificates version
  command: dpkg-query -W ca-certificates | awk '{ print $2 }' | cut -c1-8
  register: ca_certificates_check_deb
  failed_when: ca_certificates_check_deb.rc > 1
  changed_when: ca_certificates_check_deb.rc == 1

- name: Check for Zabbix release package
  command: dpkg-query -W zabbix-release
  register: zabbix_check_deb
  failed_when: zabbix_check_deb.rc > 1
  changed_when: zabbix_check_deb.rc == 1

- name: Retrieve Zabbix release package
  get_url:
    url: https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-1+ubuntu20.04_all.deb
    dest: /tmp/zabbix-release_6.0-1+ubuntu20.04_all.deb
  when: zabbix_check_deb.rc == 1

- name: Install Zabbix release package
  apt:
    deb: /tmp/zabbix-release_6.0-1+ubuntu20.04_all.deb
  when: zabbix_check_deb.rc == 1

- name: Add Zabbix Public Signing Key
  ansible.builtin.apt_key:
    url: https://repo.zabbix.com/zabbix-official-repo.key
    state: present

- name: Update sources for Ubuntu 22.04 (jammy)
  ansible.builtin.replace:
    path: /etc/apt/sources.list.d/zabbix.list
    regexp: '(\s+)focal(\s+.*)?$'
    replace: '\1jammy\2'
  become: true
  when: 
    - ansible_distribution == 'Ubuntu' 
    - ansible_distribution_release == 'jammy' 

- name: Install Zabbix agent packages
  apt:
    name:
      - zabbix-agent
    state: latest
    install_recommends: yes
    update_cache: yes
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: Install Zabbix agent template
  ansible.builtin.template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    backup: yes
  become: true
