---
- include_tasks: debian.yml
  when: ansible_distribution_file_variety == 'Debian'

- include_tasks: redhat.yml
  when: ansible_distribution_file_variety == 'RedHat'

- include_tasks: archlinux.yml
  when: ansible_distribution_file_variety == 'Archlinux'
